NOTES


* Redefinition of "import" may be tricky, as it is implicit and not in any module.
  - possible reimplement using core functionality.

* Use of "define-values" is elegant but loses lambda-info for the defined procedures.
  - Removed.

* "export" does not support "(rename ...)" specifier yet.
  - this needs extensions to the core module system.

* "(import SYMBOL)" is currently allowed. Should it not?
  - I think this is needed for backwards compatibility (when an R7RS module imports a non-R7RS module).

* Redefinition of "import" causes "re-importing" warnings.
  - The warnings could be removed in core, it's usefulness is not completely clear.

* Just reexporting procedures (like from srfi-4) doesn't change their lambda-info names.
  - This is sort of confusing, do we care?
  - Also, this makes the locations from errors (from ##sys#check-whatever) wrong/misleading.

* Should bytevectors be implemented over blobs instead of srfi-4 (or something else)?

* I think library forms (i.e. ".sld" files) should look for includes relative to themselves
  - not sure how to get that info when expanding define-library

* UTF8? Not required, but should (use r7rs) include this extension, like it includes numbers?

* get-environment-variable: "It is also an error to mutate the resulting string" ...
  - can we just ignore this?

* In R7RS parameter-values are not inherited from parent threads. This
  will require changes in core, possibly with some sort of backwards-compatibility mode.

